api/urls.py
from django.urls import include, path
from rest_framework import routers
from . import views

router = routers.DefaultRouter()
router.register('data_tk', views.DataTkViewSet)
router.register('daftar', views.DaftarViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
app_name = 'api'
urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

daftar/urls.py
from django.urls import path
from . import views

app_name = 'daftar'
urlpatterns = [
    path('', views.index, name='home'),
    # path('karyawan/<int:pk>/delete', views.karyawan_delete, name='karyawan_delete'),
    # path('karyawan/<int:pk>/edit', views.karyawan_edit, name='karyawan_edit'),
    # path('karyawan/<int:pk>/', views.karyawan_detail, name='karyawan_detail'),
    path('cari/', views.cari, name='cari'),
    path('add/<int:pk>', views.daftar_tk, name='add_tk'),
    # path('daftar/', views.karyawan_list, name='karyawan_list'),
    #path('pk_list', views.pk_list, name='pk_list'),
   


]

winback/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
# from daftar import views as daftar_views
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('login/', user_views.masuk, name='login'),
    path('logout/', user_views.singout, name='logout'),
    # path('winback/', daftar_views.index, name='winback'),
    path('api/', include('api.urls', namespace='api')),
    path('daftar/', include('daftar.urls', namespace='daftar')),
    path('', views.index, name='home'),
]

templates/navbar.html
<ul class="nav navbar-nav">
    <li class="active">
        <a href="{% url 'home' %}"><i class="menu-icon fa fa-laptop"></i>Dashboard </a>
    </li>
    <li class="menu-title">Dashboard Menu</li><!-- /.menu-title -->
    <li class="menu-item-has-children dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-male"></i>TK Winback</a>
        <ul class="sub-menu children dropdown-menu">                            <li><i class="fa fa-plus"></i><a href="{% url 'daftar:cari' %}">Pendaftaran</a></li>
            <li><i class="fa fa-id-badge"></i><a href="ui-badges.html">Badges</a></li>
            <li><i class="fa fa-bars"></i><a href="ui-tabs.html">Tabs</a></li>

            <li><i class="fa fa-id-card-o"></i><a href="ui-cards.html">Cards</a></li>
            <li><i class="fa fa-exclamation-triangle"></i><a href="ui-alerts.html">Alerts</a></li>
            <li><i class="fa fa-spinner"></i><a href="ui-progressbar.html">Progress Bars</a></li>
            <li><i class="fa fa-fire"></i><a href="ui-modals.html">Modals</a></li>
            <li><i class="fa fa-book"></i><a href="ui-switches.html">Switches</a></li>
            <li><i class="fa fa-th"></i><a href="ui-grids.html">Grids</a></li>
            <li><i class="fa fa-file-word-o"></i><a href="ui-typgraphy.html">Typography</a></li>
        </ul>
    </li>
    <li class="menu-item-has-children dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-table"></i>Tables</a>
        <ul class="sub-menu children dropdown-menu">
            <li><i class="fa fa-table"></i><a href="tables-basic.html">Basic Table</a></li>
            <li><i class="fa fa-table"></i><a href="tables-data.html">Data Table</a></li>
        </ul>
    </li>
    <li class="menu-item-has-children dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-th"></i>Forms</a>
        <ul class="sub-menu children dropdown-menu">
            <li><i class="menu-icon fa fa-th"></i><a href="forms-basic.html">Basic Form</a></li>
            <li><i class="menu-icon fa fa-th"></i><a href="forms-advanced.html">Advanced Form</a></li>
        </ul>
    </li>

    <li class="menu-title">Icons</li><!-- /.menu-title -->

    <li class="menu-item-has-children dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-tasks"></i>Icons</a>
        <ul class="sub-menu children dropdown-menu">
            <li><i class="menu-icon fa fa-fort-awesome"></i><a href="font-fontawesome.html">Font Awesome</a></li>
            <li><i class="menu-icon ti-themify-logo"></i><a href="font-themify.html">Themefy Icons</a></li>
        </ul>
    </li>
    <li>
        <a href="widgets.html"> <i class="menu-icon ti-email"></i>Widgets </a>
    </li>
    <li class="menu-item-has-children dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-bar-chart"></i>Charts</a>
        <ul class="sub-menu children dropdown-menu">
            <li><i class="menu-icon fa fa-line-chart"></i><a href="charts-chartjs.html">Chart JS</a></li>
            <li><i class="menu-icon fa fa-area-chart"></i><a href="charts-flot.html">Flot Chart</a></li>
            <li><i class="menu-icon fa fa-pie-chart"></i><a href="charts-peity.html">Peity Chart</a></li>
        </ul>
    </li>

    <li class="menu-item-has-children dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-area-chart"></i>Maps</a>
        <ul class="sub-menu children dropdown-menu">
            <li><i class="menu-icon fa fa-map-o"></i><a href="maps-gmap.html">Google Maps</a></li>
            <li><i class="menu-icon fa fa-street-view"></i><a href="maps-vector.html">Vector Maps</a></li>
        </ul>
    </li>
    <li class="menu-title">Extras</li><!-- /.menu-title -->
    <li class="menu-item-has-children dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-glass"></i>Pages</a>
        <ul class="sub-menu children dropdown-menu">
            <li><i class="menu-icon fa fa-sign-in"></i><a href="page-login.html">Login</a></li>
            <li><i class="menu-icon fa fa-sign-in"></i><a href="page-register.html">Register</a></li>
            <li><i class="menu-icon fa fa-paper-plane"></i><a href="pages-forget.html">Forget Pass</a></li>
        </ul>
    </li>
</ul>