api/urls.py
from django.urls import include, path
from rest_framework import routers
from . import views

router = routers.DefaultRouter()
router.register('data_tk', views.DataTkViewSet)
router.register('daftar', views.DaftarViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
app_name = 'api'
urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

daftar/urls.py
from django.urls import path
from . import views

app_name = 'daftar'
urlpatterns = [
    path('', views.index, name='home'),
    # path('karyawan/<int:pk>/delete', views.karyawan_delete, name='karyawan_delete'),
    # path('karyawan/<int:pk>/edit', views.karyawan_edit, name='karyawan_edit'),
    # path('karyawan/<int:pk>/', views.karyawan_detail, name='karyawan_detail'),
    path('cari/', views.cari, name='cari'),
    path('add/<int:pk>', views.daftar_tk, name='add_tk'),
    # path('daftar/', views.karyawan_list, name='karyawan_list'),
    #path('pk_list', views.pk_list, name='pk_list'),
   


]

winback/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
# from daftar import views as daftar_views
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('login/', user_views.masuk, name='login'),
    path('logout/', user_views.singout, name='logout'),
    # path('winback/', daftar_views.index, name='winback'),
    path('api/', include('api.urls', namespace='api')),
    path('daftar/', include('daftar.urls', namespace='daftar')),
    path('', views.index, name='home'),
]

daftar/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
import decimal, requests, sqlite3
from bs4 import BeautifulSoup
import json
# import crawler1
# Create your models here.


PEKERJAAN = [
('P001','PETANI/PEKEBUN'),
('P002','PETERNAK'),
('P003','NELAYAN/PERIKANAN'),
('P004','TRANSPORTASI'),
('P005','BURUH HARIAN LEPAS'),
('P006','BURUH TANI/PERKEBUNAN'),
('P007','BURUH NELAYAN/PERIKANAN'),
('P008','BURUH PETERNAKAN'),
('P009','PEMBANTU RUMAH TANGGA'),
('P010','TUKANG CUKUR'),
('P011','TUKANG LISTRIK'),
('P012','TUKANG BATU'),
('P013','TUKANG KAYU'),
('P014','TUKANG SOL SEPATU'),
('P015','TUKANG LAS/PANDAI BESI'),
('P016','TUKANG JAHIT'),
('P017','TUKANG GIGI'),
('P018','PENATA RIAS'),
('P019','PENATA BUSANA'),
('P020','PENATA RAMBUT'),
('P021','MEKANIK'),
('P022','SENIMAN'),
('P023','TABIB'),
('P024','PARAJI'),
('P025','PERANCANG BUSANA'),
('P026','PENTERJEMAH'),
('P027','IMAM MESJID'),
('P028','PENDETA'),
('P029','PASTOR'),
('P030','WARTAWAN'),
('P031','USTADZ/MUBALIGH'),
('P032','JURU MASAK'),
('P033','PROMOTOR ACARA'),
('P034','DOSEN'),
('P035','GURU'),
('P036','PENGACARA'),
('P037','NOTARIS'),
('P038','ARSITEK'),
('P039','KONSULTAN'),
('P040','DOKTER'),
('P041','BIDAN'),
('P042','APOTEKER'),
('P043','PSIKIATER/PSIKOLOG'),
('P044','PENYIAR RADIO'),
('P045','PELAUT'),
('P046','PENELITI'),
('P047','SOPIR'),
('P048','PIALANG'),
('P049','PARANORMAL'),
('P050','PEDAGANG'),
('P051','BIARAWATI'),
('P052','WIRASWASTA'),
('P053','MITRA GOJEK'),
('P054','MITRA GRAB'),
('P055','MITRA UBER'),
('P056','PEKERJA MAGANG'),
('P057','SISWA KERJA PRAKTEK'),
('P058','TENAGA HONORER (SELAIN PENYELENGGARA NEGARA)'),
('P059','NARAPIDANA DALAM PROSES ASIMILASI'),
('P060','ATLET'),
('P061','ARTIS'),
('P062','JURU PARKIR'),
('P063','TUKANG PIJAT'),
('P064','PEMANDU LAGU'),
('P065','PENDAMPING DESA'),
('P066','BURUH BONGKAR MUAT/BAGASI'),
('P067','RELAWAN TAGANA/RELAWAN BENCANA'),
('P068','TUKANG SAMPAH'),
('P069','PEMULUNG'),
('P070','MARBOT MESJID'),
('P071','MITRA GOJEK-GO LIFE'),

    
    
]

PROGRAM = [
    ('T', 'JKK & JKM'),
    ('L', 'JKK, JKM & JHT'),
]

BULAN = [
    (1, '1 Bulan'),
    (3, '3 Bulan'),
    (6, '6 Bulan'),
    (12, '12 Bulan')
]

LOKASI = [
    ('1101','ACEH SELATAN'),
    ('1102','ACEH TENGGARA'),
    ('1103','ACEH TIMUR'),
    ('1104','ACEH TENGAH'),
    ('1105','ACEH BARAT'),
    ('1106','ACEH BESAR'),
    ('1107','PIDIE'),
    ('1108','ACEH UTARA'),
    ('1109','SIMEULUE'),
    ('1110','ACEH SINGKIL'),
    ('1111','BIREUEN'),
    ('1112','ACEH BARAT DAYA'),
    ('1113','GAYO LUES'),
    ('1114','ACEH JAYA'),
    ('1115','NAGAN RAYA'),
    ('1116','ACEH TAMIANG'),
    ('1117','BENER MERIAH'),
    ('1118','PIDIE JAYA'),
    ('1171','KOTA BANDA ACEH'),
    ('1172','KOTA SABANG'),
    ('1173','KOTA LHOKSEUMAWE'),
    ('1174','KOTA LANGSA'),
    ('1175','KOTA SUBULUSSALAM'),

]

# class User(models.Model):
#     user_id = models.CharField(max_length=8)
#     passwd = models.CharField(max_length=16)
#     role = models.IntegerField(choices=ROLE)
#     nama = models.CharField(max_length=50)

class DataTK(models.Model):
    nik = models.CharField(max_length=16, blank=False)
    nama = models.CharField(max_length=50)
    tempat_lhr = models.CharField(max_length=30)
    tgl_lhr = models.CharField(max_length=10)
    alamat = models.TextField()

    # def __str__(self, tonik):

        
            
        
    

    # def getjson(self):
    #     r = crawler1(y)
   

class Daftar(models.Model):
    nik = models.ForeignKey(DataTK, on_delete=models.CASCADE)   
    mail = models.EmailField()    
    no_hp = models.CharField(max_length=15)
    pekerjaan1 = models.CharField(choices=PEKERJAAN, max_length=50)
    pekerjaan2 = models.CharField(choices=PEKERJAAN, max_length=50, blank=True)
    lokasi = models.CharField(choices=LOKASI, max_length=30)
    penghasilan = models.FloatField()
    program = models.CharField(choices=PROGRAM, max_length=12)
    bulan = models.IntegerField(choices=BULAN)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    tgl_buat = models.DateTimeField(auto_now_add=True)
    # total = models.DecimalField(max_digits=10, decimal_places=2)
    def total(self):

        if (self.program == 1):
            jkk = decimal.Decimal(self.penghasilan) * decimal.Decimal('0.01')
            jkm = 6800
            bln = self.bulan
            self.total = bln * (jkk + jkm)
            # return self.total
        else:
            jkk = decimal.Decimal(self.penghasilan) * decimal.Decimal('0.01')
            jht = decimal.Decimal(self.penghasilan) * decimal.Decimal('0.02')
            jkm = 6800
            bln = self.bulan
            self.total = self.bulan * (jkk + jht + jkm)
        return self.total

daftar/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from django.db.models import Q
from django.contrib.auth.models import User
from django.contrib import messages
from django.forms.formsets import formset_factory
from .models import Daftar, DataTK
from .form import DaftarForm, DataTkForm
import sqlite3, collections, json
from .crawler1 import crawler
import requests

# import json, requests, urllib

def index(request):

    datas = Daftar.objects.select_related('nik')
    # daftar = Daftar.objects.all()
    # data = DataTK.objects.all()
    # datas = DataTK.objects.all()
    # print(datas)
    return render(request, 'daftar/winback_list.html', {'datas':datas})

def cari(request):
   
    if request.method == 'POST':
        nik = request.POST['ktp']
        
        if not nik:
            messages.error(request, 'NIK tidak boleh kosong')
            return render(request, 'daftar/cari.html')
        else:
            crawler(nik)
            if nik:
                
                match = DataTK.objects.filter(Q(nik__icontains=nik))
            
                
                if match:
                    
                    return render(request, 'daftar/cari.html', {'match': match})
                    # return redirect('add/')
                else:
                    messages.error(request, 'NIK tidak ditemukan')
            else:
                
                return HttpResponse('Sukses')
        
    return render(request, 'daftar/cari.html') 
    
def daftar_tk(request, pk):

    data_master = get_object_or_404(DataTK, pk=pk)
    # DataTKFormSet = formset_factory(DataTK)
    if request.method == "POST":
        form = DaftarForm(request.POST, instance=data_master)
        # formset = DataTKFormSet(request.POST)
        if form.is_valid():
            # , formset.is_valid()]):
            post = form.save(commit=False)
            post.user_id = request.user
            post = form.save()
            # post.save()
            # for set_form in formset:
            #     if set_form.cleaned_data:
            #         reg = set_form.save(commit=False)
            #         reg.user_id = request.user
            #         reg.nik = post
            #         reg.save()
            # nik = form.cleaned_data.get('nik')
            # karyawan_created.delay(post.id)
            # karyawan_jatuh_tempo.apply_async((post.id,),
            #                                  countdown=60)
            return redirect('daftar:home', pk=data_master)
    else:
        form = DaftarForm(instance=data_master)
        # formset = DataTKFormSet()

    return render(request, 'daftar/winback_new.html', {'form': form})

# def getJson(request):
#     response = requests.get('http://localhost:8000/api/data_tk/')
#     data = response.json()
#     return render(request, 'daftar/winback_new.html', {
#         'nik':data['nik'],
#         'nama':data['nama'],
#         'tempat':data['tempat_lhr'],
#         'tgl_lhr':data['tgl_lhr'],
#         'alamat':data['alamat']
#     })

daftar/templates/daftar/cari.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block content %}
    <div class="breadcrumbs">
            <div class="breadcrumbs-inner">
                <div class="row m-0">
                    <div class="col-sm-4">
                        <div class="page-header float-left">
                            <div class="page-title">
                                <h1>Dashboard</h1>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-8">
                        <div class="page-header float-right">
                            <div class="page-title">
                                <ol class="breadcrumb text-right">
                                    <li><a href="#">Dashboard</a></li>
                                    <li><a href="#">Daftar</a></li>
                                    <li class="active">CARI NIK</li>
                                </ol>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="content">
            {% if messages %}
                
                {% for message in messages %}
                        <div class="sufee-alert alert with-close alert-danger alert-dismissible fade show">
                            <span class="badge badge-pill badge-danger">PERINGATAN!</span>
                                {{ message }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                {% endfor %}
            {% endif %}
            <div class="animated fadeIn">

                <div class="row">

                    <div class="col-xs-8 col-sm-8">
                        <div class="card">
                            <div class="card-header">
                                <strong>CARI NIK</strong>
                            </div>
                            <div class="card-body card-block">
                             <form method="post" enctype="multipart/form-data" class="form-horizontal">
                                {% csrf_token %}
                                <div class="form-group">
                                  <div class="row m-2">
                                   <div class="col">
                                    <label class=" form-control-label">INPUT NIK</label>
                                    <div class="input-group">
                                        <div class="input-group-addon"><i class="fa fa-calendar"></i></div>
                                        <input class="form-control" name="ktp" style="margin-left: 5px">
                                    </div>
                                    <div class="row">
                                    <div class="col" align="right" style="padding-top : 15px">
                                       
                                        <button type="submit" class="btn btn-success" id="cari">Cari</button>
                                       
                                    </div>
                                    </div>
                                   </div>
                                  </div>
                                    <small class="form-text text-muted">cth. 1270111100001111</small>
                                </div>
                                
                             </form>
                            </div> <!--card body-->
                        </div>
                    </div>


          </div>

      </div>
        <div class="col-xs-6 col-sm-8">
         <div class="table-stats order-table ov-h">
            <table class="table ">
                <thead>
                    <tr align="center">
                        <th class="serial">No</th>
                        <th>NIK</th>
                        <th>Nama</th>
                        <th>Tempat Lahir</th>
                        <th>Tanggal Lahir</th>
                        <th>Alamat</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for matches in match %}
                    <tr align="center">
                        <td class="serial">{{ forloop.counter }}</td>
                        <td> {{matches.nik}} </td>
                        <td>  <span class="name">{{ matches.nama }}</span> </td>
                        <td> <span class="product">{{ matches.tempat_lhr }}</span> </td>
                        <td>{{ matches.tgl_lhr }}</td>
                        <td>{{ matches.alamat }}
                        <td>
                            <a href="{% url 'daftar:add_tk' pk=matches.pk %}" class="btn btn-primary" role="button">Daftarkan</a>

                        </td>
                    </tr>
                     {% endfor %}                                                                               
                </tbody>
            </table>
        </div>     
  </div>
</div>

</div><!-- .animated -->
</div><!-- .content -->
{% endblock content %}

daftar/templates/daftar/winback_list.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block content %}
    <!-- Orders -->
<div class="orders">
    <div class="row">
        <div class="col-xl-12">
            <div class="card">
                <div class="card-body">
                    <h4 class="box-title">Laporan Pendaftaran TK Winback </h4>
                </div>
                <div class="card-body--">
                    <div class="table-stats order-table ov-h">
                        <table class="table ">
                            <thead>
                                <tr>
                                    <th class="serial">No</th>
                                    <th>NIK</th>
                                    <th>Nama</th>
                                    <th>Tempat/<br/>Tgl. Lahir</th>
                                    <th>Alamat</th>
                                    <th>Pekerjaan</th>
                                    <th>Lokasi</th>
                                    <th>Penghasilan</th>
                                    <th>Program</th>
                                    <th>Priode<br/>Program</th>
                                    <th>Total</th>
                                    <th>User</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for data in datas %}
                                    
                                <tr>
                                
                                    <td class="serial">{{ forloop.counter }}</td>
                                    <td> {{data.nik}} </td>
                                    <td>  <span class="name">{{data.nama}}</span> </td>
                                    <td> {{data.tempat_lhr}}/<br/>{{data.tgl_lhr}} </td>
                                    <td> {{data.alamat}} </td>
                                    <td> {{data.pekerjaan}} </td>
                                    <td> {{data.lokasi}} </td>
                                    <td> <span class="price">Rp.{{data.penghasilan|intcomma}}</span> </td>
                                    <td> {{data.get_program_display}}</td>
                                    <td> {{data.get_bulan_display}}</td>
                                    <td> <span class="price">Rp.{{data.total|intcomma}}</span> </td>
                                    <td>
                                        <span class="badge badge-complete">Complete</span>
                                    </td>
                                </tr>
                                    
                                {% endfor %}
                            </tbody>
                        </table>
                    </div> <!-- /.table-stats -->
                </div>
            </div> <!-- /.card -->
        </div>  <!-- /.col-lg-8 -->

        
    </div>
</div>
<!-- /.orders -->
{% endblock content %}

daftar/templates/daftar/winback_new.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block content %}
    <div class="breadcrumbs">
            <div class="breadcrumbs-inner">
                <div class="row m-0">
                    <div class="col-sm-4">
                        <div class="page-header float-left">
                            <div class="page-title">
                                <h1>Dashboard</h1>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-8">
                        <div class="page-header float-right">
                            <div class="page-title">
                                <ol class="breadcrumb text-right">
                                    <li><a href="#">Dashboard</a></li>
                                    <li><a href="#">Daftar</a></li>
                                    <li class="active">Tambah TK</li>
                                </ol>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="content">
            <div class="animated fadeIn">

                <div class="row">

                    <div class="col-xs-6 col-sm-6">
                        <div class="card">
                            <div class="card-header">
                                <strong>Pendaftaran TK</strong>
                            </div>
                            <div class="card-body card-block">
                             <form action="" method="post" class="form-horizontal" novalidate="novalidate">
                                {% csrf_token %}
                                
                                <div class="form-group">
                                    <label class=" form-control-label">Email</label>
                                    <div class="input-group">
                                        <div class="input-group-addon"><i class="fa fa-envelope"></i></div>
                                        {{form.mail}}
                                        {{form.mail.errors}}
                                    </div>
                                    <small class="form-text text-muted">cth. john.doe@gmail.com</small>
                                </div>
                                <div class="form-group">
                                    <label class=" form-control-label">No HP</label>
                                    <div class="input-group">
                                        <div class="input-group-addon"><i class="fa fa-mobile"></i></div>
                                        {{form.no_hp}}
                                        {{form.no_hp.errors}}
                                    </div>
                                    <small class="form-text text-muted">cth. 082200220022</small>
                                </div>
                                <div class="form-group">
                                    <label class=" form-control-label">Pekerjaan 1</label>
                                    <div class="input-group">
                                        <div class="input-group-addon"><i class="fa fa-briefcase"></i></div>
                                        {{form.pekerjaan1}}
                                        {{form.pekerjaan1.errors}}
                                    </div>
                                    <small class="form-text text-muted">cth. Petani</small>
                                </div>
                                <div class="form-group">
                                    <label class=" form-control-label">Pekerjaan 2</label>
                                    <div class="input-group">
                                        <div class="input-group-addon"><i class="fa fa-briefcase"></i></div>
                                        {{form.pekerjaan2}}
                                        {{form.pekerjaan2.errors}}
                                    </div>
                                    <small class="form-text text-muted">cth. Nelayan</small>
                                </div>
                                <div class="form-group">
                                    <label class=" form-control-label">Lokasi</label>
                                    <div class="input-group">
                                        <div class="input-group-addon"><i class="fa fa-briefcase"></i></div>
                                        {{form.lokasi}}
                                        {{form.lokasi.errors}}
                                    </div>
                                    <small class="form-text text-muted">ex. Langsa</small>
                                </div>
                                <div class="form-group">
                                    <label class=" form-control-label">Penghasilan</label>
                                    <div class="input-group">
                                        <div class="input-group-addon"><i class="fa fa-money"></i></div>
                                        {{form.penghasilan}}
                                        {{form.penghasilan.errors}}
                                    </div>
                                    <small class="form-text text-muted">cth. 1000000</small>
                                </div>
                                <div class="form-group">
                                    <label class=" form-control-label">Program</label>
                                    <div class="input-group">
                                        <div class="input-group-addon"><i class="fa fa-bars" aria-hidden="true"></i></div>
                                        {{form.program}}
                                        {{form.program.errors}}
                                    </div>
                                    <small class="form-text text-muted">cth. JKK dan JKM</small>
                                </div>
                                <div class="form-group">
                                    <label class=" form-control-label">Bulan</label>
                                    <div class="input-group">
                                        <div class="input-group-addon"><i class="fa fa-clock-o" aria-hidden="true"></i></div>
                                        {{form.bulan}}
                                        {{form.bulan.errors}}
                                    </div>
                                    <small class="form-text text-muted">cth. 1 Bulan</small>
                                </div>
                                <div class="row">
                                <div class="col-xs-8 col-sm-12" align="right">
                                <button type="submit" class="btn btn-primary btn-flat m-b-30 m-t-30">Submit</button>
                                </div>
                                </div>
                             </form>
                            </div> <!--card body-->
                        </div>
                    </div>

                    {% comment %} <div class="col-xs-6 col-sm-6">
                        <div class="card">
                            <div class="card-header">
                                <strong class="card-title">Standard Select</strong>
                            </div>
                            <div class="card-body">

                              <select data-placeholder="Choose a Country..." class="standardSelect" tabindex="1">
                                <option value="" label="default"></option>
                                <option value="United States">United States</option>
                                <option value="United Kingdom">United Kingdom</option>
                                <option value="Afghanistan">Afghanistan</option>
                                <option value="Aland Islands">Aland Islands</option>
                                <option value="Albania">Albania</option>
                                <option value="Algeria">Algeria</option>
                                <option value="American Samoa">American Samoa</option>
                                <option value="Andorra">Andorra</option>
                                <option value="Angola">Angola</option>
                                <option value="Anguilla">Anguilla</option>
                                <option value="Antarctica">Antarctica</option>
                            </select>
                        </div>
                    </div>

                    <div class="card">
                        <div class="card-header">
                            <strong class="card-title">Multi Select</strong>
                        </div>
                        <div class="card-body">

                          <select data-placeholder="Choose a country..." multiple class="standardSelect">
                            <option value="" label="default"></option>
                            <option value="United States">United States</option>
                            <option value="United Kingdom">United Kingdom</option>
                            <option value="Afghanistan">Afghanistan</option>
                            <option value="Aland Islands">Aland Islands</option>
                            <option value="Albania">Albania</option>
                            <option value="Algeria">Algeria</option>
                            <option value="American Samoa">American Samoa</option>
                            <option value="Andorra">Andorra</option>
                            <option value="Angola">Angola</option>
                            <option value="Anguilla">Anguilla</option>
                            <option value="Antarctica">Antarctica</option>
                        </select>

                    </div>
                </div>

                <div class="card">
                    <div class="card-header">
                        <strong class="card-title">Multi Select with Groups</strong>
                    </div>
                    <div class="card-body">

                      <select data-placeholder="Your Favorite Football Team" multiple class="standardSelect" tabindex="5">
                        <option value="" label="default"></option>
                        <optgroup label="NFC EAST">
                          <option>Dallas Cowboys</option>
                          <option>New York Giants</option>
                          <option>Philadelphia Eagles</option>
                          <option>Washington Redskins</option>
                      </optgroup>
                      <optgroup label="NFC NORTH">
                          <option>Chicago Bears</option>
                          <option>Detroit Lions</option>
                          <option>Green Bay Packers</option>
                          <option>Minnesota Vikings</option>
                      </optgroup>
                      <optgroup label="NFC SOUTH">
                          <option>Atlanta Falcons</option>
                          <option>Carolina Panthers</option>
                          <option>New Orleans Saints</option>
                          <option>Tampa Bay Buccaneers</option>
                      </optgroup>
                      <optgroup label="NFC WEST">
                          <option>Arizona Cardinals</option>
                          <option>St. Louis Rams</option>
                          <option>San Francisco 49ers</option>
                          <option>Seattle Seahawks</option>
                      </optgroup>
                      <optgroup label="AFC EAST">
                          <option>Buffalo Bills</option>
                          <option>Miami Dolphins</option>
                          <option>New England Patriots</option>
                          <option>New York Jets</option>
                      </optgroup>
                      <optgroup label="AFC NORTH">
                          <option>Baltimore Ravens</option>
                          <option>Cincinnati Bengals</option>
                          <option>Cleveland Browns</option>
                          <option>Pittsburgh Steelers</option>
                      </optgroup>
                      <optgroup label="AFC SOUTH">
                          <option>Houston Texans</option>
                          <option>Indianapolis Colts</option>
                          <option>Jacksonville Jaguars</option>
                          <option>Tennessee Titans</option>
                      </optgroup>
                      <optgroup label="AFC WEST">
                          <option>Denver Broncos</option>
                          <option>Kansas City Chiefs</option>
                          <option>Oakland Raiders</option>
                          <option>San Diego Chargers</option>
                      </optgroup>
                  </select>

              </div> {% endcomment %}
          </div>

      </div>



  </div>


</div><!-- .animated -->
</div><!-- .content -->
{% endblock content %}